
// This file has been generated by the GUI designer. Do not modify.
namespace maxim_11311
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button tbnQuit;
		
		private global::Gtk.ToggleButton tbnConnect;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Notebook notebook2;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Button btnClear;
		
		private global::Gtk.Button btnReadAll;
		
		private global::Gtk.Button btnReadReg;
		
		private global::Gtk.Button btnWriteReg;
		
		private global::Gtk.Label lblReadRes;
		
		private global::Gtk.SpinButton spbReadReg;
		
		private global::Gtk.SpinButton spbWriteReg;
		
		private global::Gtk.SpinButton spbWriteVal;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView txvLog;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget maxim_11311.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "maxim_11311.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child maxim_11311.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'/></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tbnQuit = new global::Gtk.Button ();
			this.tbnQuit.CanFocus = true;
			this.tbnQuit.Name = "tbnQuit";
			this.tbnQuit.UseUnderline = true;
			this.tbnQuit.Label = global::Mono.Unix.Catalog.GetString ("Quit");
			this.hbox1.Add (this.tbnQuit);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tbnQuit]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tbnConnect = new global::Gtk.ToggleButton ();
			this.tbnConnect.CanFocus = true;
			this.tbnConnect.Name = "tbnConnect";
			this.tbnConnect.UseUnderline = true;
			this.tbnConnect.Label = global::Mono.Unix.Catalog.GetString ("Connect");
			this.hbox1.Add (this.tbnConnect);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tbnConnect]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnClear = new global::Gtk.Button ();
			this.btnClear.CanFocus = true;
			this.btnClear.Name = "btnClear";
			this.btnClear.UseUnderline = true;
			this.btnClear.Label = global::Mono.Unix.Catalog.GetString ("Clear log");
			this.table1.Add (this.btnClear);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnClear]));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnReadAll = new global::Gtk.Button ();
			this.btnReadAll.CanFocus = true;
			this.btnReadAll.Name = "btnReadAll";
			this.btnReadAll.UseUnderline = true;
			this.btnReadAll.Label = global::Mono.Unix.Catalog.GetString ("Read all");
			this.table1.Add (this.btnReadAll);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnReadAll]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnReadReg = new global::Gtk.Button ();
			this.btnReadReg.CanFocus = true;
			this.btnReadReg.Name = "btnReadReg";
			this.btnReadReg.UseUnderline = true;
			this.btnReadReg.Label = global::Mono.Unix.Catalog.GetString ("Read register");
			this.table1.Add (this.btnReadReg);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnReadReg]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnWriteReg = new global::Gtk.Button ();
			this.btnWriteReg.CanFocus = true;
			this.btnWriteReg.Name = "btnWriteReg";
			this.btnWriteReg.UseUnderline = true;
			this.btnWriteReg.Label = global::Mono.Unix.Catalog.GetString ("Write register");
			this.table1.Add (this.btnWriteReg);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnWriteReg]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblReadRes = new global::Gtk.Label ();
			this.lblReadRes.Name = "lblReadRes";
			this.table1.Add (this.lblReadRes);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblReadRes]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spbReadReg = new global::Gtk.SpinButton (0, 127, 1);
			this.spbReadReg.CanFocus = true;
			this.spbReadReg.Name = "spbReadReg";
			this.spbReadReg.Adjustment.PageIncrement = 10;
			this.spbReadReg.ClimbRate = 1;
			this.spbReadReg.Numeric = true;
			this.table1.Add (this.spbReadReg);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.spbReadReg]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spbWriteReg = new global::Gtk.SpinButton (0, 127, 1);
			this.spbWriteReg.CanFocus = true;
			this.spbWriteReg.Name = "spbWriteReg";
			this.spbWriteReg.Adjustment.PageIncrement = 10;
			this.spbWriteReg.ClimbRate = 1;
			this.spbWriteReg.Numeric = true;
			this.table1.Add (this.spbWriteReg);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.spbWriteReg]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spbWriteVal = new global::Gtk.SpinButton (0, 65535, 1);
			this.spbWriteVal.CanFocus = true;
			this.spbWriteVal.Name = "spbWriteVal";
			this.spbWriteVal.Adjustment.PageIncrement = 10;
			this.spbWriteVal.ClimbRate = 1;
			this.spbWriteVal.Numeric = true;
			this.table1.Add (this.spbWriteVal);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.spbWriteVal]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox7.Add (this.table1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.table1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txvLog = new global::Gtk.TextView ();
			this.txvLog.CanFocus = true;
			this.txvLog.Name = "txvLog";
			this.GtkScrolledWindow.Add (this.txvLog);
			this.hbox7.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.GtkScrolledWindow]));
			w16.Position = 1;
			this.notebook2.Add (this.hbox7);
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
			this.notebook2.SetTabLabel (this.hbox7, this.label5);
			this.label5.ShowAll ();
			this.hbox2.Add (this.notebook2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.notebook2]));
			w18.Position = 0;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w19.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox2.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar1]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w22.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 636;
			this.DefaultHeight = 594;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.tbnQuit.Clicked += new global::System.EventHandler (this.OnTbnQuitClicked);
			this.tbnConnect.Toggled += new global::System.EventHandler (this.OnTbnConnectToggled);
			this.spbReadReg.ValueChanged += new global::System.EventHandler (this.OnSpbReadRegValueChanged);
			this.btnWriteReg.Clicked += new global::System.EventHandler (this.OnBtnWriteRegClicked);
			this.btnReadReg.Clicked += new global::System.EventHandler (this.OnBtnReadRegClicked);
			this.btnReadAll.Clicked += new global::System.EventHandler (this.OnBtnReadAllClicked);
			this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearClicked);
		}
	}
}
