
// This file has been generated by the GUI designer. Do not modify.
namespace maxim_11311
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button tbnQuit;
		
		private global::Gtk.ToggleButton tbnConnect;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Notebook notebook2;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label lblP;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label lblP1;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Table tblPortConf;
		
		private global::Gtk.Button btnPortConfApply;
		
		private global::Gtk.CheckButton cbxPortConfInvert;
		
		private global::Gtk.ComboBox cmbPortConfAssoc;
		
		private global::Gtk.ComboBox cmbPortConfNSamples;
		
		private global::Gtk.ComboBox cmbPortMode;
		
		private global::Gtk.ComboBox cmbPortNumber;
		
		private global::Gtk.ComboBox cmbPortRange;
		
		private global::Gtk.Label lblPortConfAssocPort;
		
		private global::Gtk.Label lblPortConfInvert;
		
		private global::Gtk.Label lblPortConfMode;
		
		private global::Gtk.Label lblPortConfNSamples;
		
		private global::Gtk.Label lblPortConfNumber;
		
		private global::Gtk.Label lblPortConfRange;
		
		private global::Gtk.Label frmPortConfig;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.VBox vbox11;
		
		private global::Gtk.VBox vbox14;
		
		private global::Gtk.VBox vbox13;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label GtkLabel19;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.RadioButton rbnAdcIdleMode;
		
		private global::Gtk.RadioButton rbnAdcSingleSweep;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.RadioButton rbnAdcSingleConv;
		
		private global::Gtk.RadioButton rbnAdcContSweep;
		
		private global::Gtk.Label lblADCConvMode;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.RadioButton rbnAdcSpeed200;
		
		private global::Gtk.RadioButton rbnAdcSpeed250;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.RadioButton rbnAdcSpeed333;
		
		private global::Gtk.RadioButton rbnAdcSpeed400;
		
		private global::Gtk.Label GtkLabel13;
		
		private global::Gtk.Label GtkLabel11;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Button btnClear;
		
		private global::Gtk.Button btnReadAll;
		
		private global::Gtk.Button btnReadReg;
		
		private global::Gtk.Button btnWriteReg;
		
		private global::Gtk.Label lblReadRes;
		
		private global::Gtk.SpinButton spbReadReg;
		
		private global::Gtk.SpinButton spbWriteReg;
		
		private global::Gtk.SpinButton spbWriteVal;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView txvLog;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget maxim_11311.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "maxim_11311.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child maxim_11311.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'/></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tbnQuit = new global::Gtk.Button ();
			this.tbnQuit.CanFocus = true;
			this.tbnQuit.Name = "tbnQuit";
			this.tbnQuit.UseUnderline = true;
			this.tbnQuit.Label = global::Mono.Unix.Catalog.GetString ("Quit");
			this.hbox1.Add (this.tbnQuit);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tbnQuit]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tbnConnect = new global::Gtk.ToggleButton ();
			this.tbnConnect.CanFocus = true;
			this.tbnConnect.Name = "tbnConnect";
			this.tbnConnect.UseUnderline = true;
			this.tbnConnect.Label = global::Mono.Unix.Catalog.GetString ("Connect");
			this.hbox1.Add (this.tbnConnect);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tbnConnect]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblP = new global::Gtk.Label ();
			this.lblP.Name = "lblP";
			this.lblP.LabelProp = global::Mono.Unix.Catalog.GetString ("Port 0");
			this.hbox5.Add (this.lblP);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblP]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			this.hbox5.Add (this.hbox9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hbox9]));
			w7.Position = 2;
			this.vbox9.Add (this.hbox5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox5]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblP1 = new global::Gtk.Label ();
			this.lblP1.Name = "lblP1";
			this.lblP1.LabelProp = global::Mono.Unix.Catalog.GetString ("Port 1");
			this.hbox6.Add (this.lblP1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblP1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			this.hbox6.Add (this.hbox10);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hbox10]));
			w10.Position = 2;
			this.vbox9.Add (this.hbox6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox6]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			// Container child frame5.Gtk.Container+ContainerChild
			this.tblPortConf = new global::Gtk.Table (((uint)(2)), ((uint)(7)), false);
			this.tblPortConf.Name = "tblPortConf";
			this.tblPortConf.RowSpacing = ((uint)(6));
			this.tblPortConf.ColumnSpacing = ((uint)(6));
			this.tblPortConf.BorderWidth = ((uint)(2));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.btnPortConfApply = new global::Gtk.Button ();
			this.btnPortConfApply.CanFocus = true;
			this.btnPortConfApply.Name = "btnPortConfApply";
			this.btnPortConfApply.UseUnderline = true;
			this.btnPortConfApply.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.tblPortConf.Add (this.btnPortConfApply);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.btnPortConfApply]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(6));
			w12.RightAttach = ((uint)(7));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.cbxPortConfInvert = new global::Gtk.CheckButton ();
			this.cbxPortConfInvert.CanFocus = true;
			this.cbxPortConfInvert.Name = "cbxPortConfInvert";
			this.cbxPortConfInvert.Label = global::Mono.Unix.Catalog.GetString ("Invert");
			this.cbxPortConfInvert.DrawIndicator = true;
			this.cbxPortConfInvert.UseUnderline = true;
			this.tblPortConf.Add (this.cbxPortConfInvert);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.cbxPortConfInvert]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.cmbPortConfAssoc = global::Gtk.ComboBox.NewText ();
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("0"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("7"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
			this.cmbPortConfAssoc.AppendText (global::Mono.Unix.Catalog.GetString ("11"));
			this.cmbPortConfAssoc.Name = "cmbPortConfAssoc";
			this.cmbPortConfAssoc.Active = 0;
			this.tblPortConf.Add (this.cmbPortConfAssoc);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.cmbPortConfAssoc]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(5));
			w14.RightAttach = ((uint)(6));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.cmbPortConfNSamples = global::Gtk.ComboBox.NewText ();
			this.cmbPortConfNSamples.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.cmbPortConfNSamples.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.cmbPortConfNSamples.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.cmbPortConfNSamples.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.cmbPortConfNSamples.AppendText (global::Mono.Unix.Catalog.GetString ("16"));
			this.cmbPortConfNSamples.AppendText (global::Mono.Unix.Catalog.GetString ("32"));
			this.cmbPortConfNSamples.AppendText (global::Mono.Unix.Catalog.GetString ("64"));
			this.cmbPortConfNSamples.AppendText (global::Mono.Unix.Catalog.GetString ("128"));
			this.cmbPortConfNSamples.Name = "cmbPortConfNSamples";
			this.cmbPortConfNSamples.Active = 0;
			this.tblPortConf.Add (this.cmbPortConfNSamples);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.cmbPortConfNSamples]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(4));
			w15.RightAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.cmbPortMode = global::Gtk.ComboBox.NewText ();
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("High impedance"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Digital input, GPI"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Level translator"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Register output, GPO"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Path output, GPO"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("DAC output"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("DAC out, ADC-monitored"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Single ended ADC"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Differential ADC +"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Differential ADC -"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Pseudo differential"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Analog switch GPI"));
			this.cmbPortMode.AppendText (global::Mono.Unix.Catalog.GetString ("Analog switch Register"));
			this.cmbPortMode.AppendText ("");
			this.cmbPortMode.AppendText ("");
			this.cmbPortMode.AppendText ("");
			this.cmbPortMode.Name = "cmbPortMode";
			this.cmbPortMode.Active = 12;
			this.tblPortConf.Add (this.cmbPortMode);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.cmbPortMode]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.cmbPortNumber = global::Gtk.ComboBox.NewText ();
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("0"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("7"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
			this.cmbPortNumber.AppendText (global::Mono.Unix.Catalog.GetString ("11"));
			this.cmbPortNumber.Name = "cmbPortNumber";
			this.cmbPortNumber.Active = 0;
			this.tblPortConf.Add (this.cmbPortNumber);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.cmbPortNumber]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.cmbPortRange = global::Gtk.ComboBox.NewText ();
			this.cmbPortRange.AppendText (global::Mono.Unix.Catalog.GetString ("none"));
			this.cmbPortRange.AppendText (global::Mono.Unix.Catalog.GetString ("0 .. +10 V"));
			this.cmbPortRange.AppendText (global::Mono.Unix.Catalog.GetString ("-5 .. +5 V"));
			this.cmbPortRange.AppendText (global::Mono.Unix.Catalog.GetString ("-10 .. 0 V"));
			this.cmbPortRange.AppendText (global::Mono.Unix.Catalog.GetString ("0 .. +2.5 V"));
			this.cmbPortRange.AppendText (global::Mono.Unix.Catalog.GetString ("res"));
			this.cmbPortRange.AppendText (global::Mono.Unix.Catalog.GetString ("0 .. +2.5 V"));
			this.cmbPortRange.Name = "cmbPortRange";
			this.cmbPortRange.Active = 0;
			this.tblPortConf.Add (this.cmbPortRange);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.cmbPortRange]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(2));
			w18.RightAttach = ((uint)(3));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.lblPortConfAssocPort = new global::Gtk.Label ();
			this.lblPortConfAssocPort.Name = "lblPortConfAssocPort";
			this.lblPortConfAssocPort.LabelProp = global::Mono.Unix.Catalog.GetString ("Ass.port");
			this.tblPortConf.Add (this.lblPortConfAssocPort);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.lblPortConfAssocPort]));
			w19.LeftAttach = ((uint)(5));
			w19.RightAttach = ((uint)(6));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.lblPortConfInvert = new global::Gtk.Label ();
			this.lblPortConfInvert.Name = "lblPortConfInvert";
			this.lblPortConfInvert.LabelProp = global::Mono.Unix.Catalog.GetString ("Invert");
			this.tblPortConf.Add (this.lblPortConfInvert);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.lblPortConfInvert]));
			w20.LeftAttach = ((uint)(3));
			w20.RightAttach = ((uint)(4));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.lblPortConfMode = new global::Gtk.Label ();
			this.lblPortConfMode.Name = "lblPortConfMode";
			this.lblPortConfMode.LabelProp = global::Mono.Unix.Catalog.GetString ("Configuration");
			this.tblPortConf.Add (this.lblPortConfMode);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.lblPortConfMode]));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.lblPortConfNSamples = new global::Gtk.Label ();
			this.lblPortConfNSamples.Name = "lblPortConfNSamples";
			this.lblPortConfNSamples.LabelProp = global::Mono.Unix.Catalog.GetString ("#Samples");
			this.tblPortConf.Add (this.lblPortConfNSamples);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.lblPortConfNSamples]));
			w22.LeftAttach = ((uint)(4));
			w22.RightAttach = ((uint)(5));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.lblPortConfNumber = new global::Gtk.Label ();
			this.lblPortConfNumber.Name = "lblPortConfNumber";
			this.lblPortConfNumber.Ypad = 5;
			this.lblPortConfNumber.LabelProp = global::Mono.Unix.Catalog.GetString ("Port number");
			this.tblPortConf.Add (this.lblPortConfNumber);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.lblPortConfNumber]));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPortConf.Gtk.Table+TableChild
			this.lblPortConfRange = new global::Gtk.Label ();
			this.lblPortConfRange.Name = "lblPortConfRange";
			this.lblPortConfRange.LabelProp = global::Mono.Unix.Catalog.GetString ("Range");
			this.tblPortConf.Add (this.lblPortConfRange);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tblPortConf [this.lblPortConfRange]));
			w24.LeftAttach = ((uint)(2));
			w24.RightAttach = ((uint)(3));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			this.frame5.Add (this.tblPortConf);
			this.frmPortConfig = new global::Gtk.Label ();
			this.frmPortConfig.Name = "frmPortConfig";
			this.frmPortConfig.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Port configuration</b>");
			this.frmPortConfig.UseMarkup = true;
			this.frame5.LabelWidget = this.frmPortConfig;
			this.vbox9.Add (this.frame5);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.frame5]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox8.Add (this.vbox9);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox9]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			this.vbox8.Add (this.vbox10);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox10]));
			w28.Position = 1;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			this.vbox11.Add (this.vbox14);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox14]));
			w29.Position = 1;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			this.vbox13.Add (this.hbox8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox8]));
			w30.Position = 1;
			this.vbox11.Add (this.vbox13);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox13]));
			w31.Position = 2;
			this.vbox8.Add (this.vbox11);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox11]));
			w32.Position = 2;
			this.GtkAlignment3.Add (this.vbox8);
			this.frame4.Add (this.GtkAlignment3);
			this.GtkLabel19 = new global::Gtk.Label ();
			this.GtkLabel19.Name = "GtkLabel19";
			this.GtkLabel19.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GtkFrame</b>");
			this.GtkLabel19.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel19;
			this.notebook2.Add (this.frame4);
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
			this.notebook2.SetTabLabel (this.frame4, this.label2);
			this.label2.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.rbnAdcIdleMode = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Idle mode"));
			this.rbnAdcIdleMode.CanFocus = true;
			this.rbnAdcIdleMode.Name = "rbnAdcIdleMode";
			this.rbnAdcIdleMode.DrawIndicator = true;
			this.rbnAdcIdleMode.UseUnderline = true;
			this.rbnAdcIdleMode.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox4.Add (this.rbnAdcIdleMode);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rbnAdcIdleMode]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.rbnAdcSingleSweep = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Single sweep"));
			this.rbnAdcSingleSweep.CanFocus = true;
			this.rbnAdcSingleSweep.Name = "rbnAdcSingleSweep";
			this.rbnAdcSingleSweep.DrawIndicator = true;
			this.rbnAdcSingleSweep.UseUnderline = true;
			this.rbnAdcSingleSweep.Group = this.rbnAdcIdleMode.Group;
			this.vbox4.Add (this.rbnAdcSingleSweep);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rbnAdcSingleSweep]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.rbnAdcSingleConv = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Single conversion"));
			this.rbnAdcSingleConv.CanFocus = true;
			this.rbnAdcSingleConv.Name = "rbnAdcSingleConv";
			this.rbnAdcSingleConv.DrawIndicator = true;
			this.rbnAdcSingleConv.UseUnderline = true;
			this.rbnAdcSingleConv.Group = this.rbnAdcIdleMode.Group;
			this.vbox5.Add (this.rbnAdcSingleConv);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.rbnAdcSingleConv]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.rbnAdcContSweep = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Continiuous sweep"));
			this.rbnAdcContSweep.CanFocus = true;
			this.rbnAdcContSweep.Name = "rbnAdcContSweep";
			this.rbnAdcContSweep.DrawIndicator = true;
			this.rbnAdcContSweep.UseUnderline = true;
			this.rbnAdcContSweep.Group = this.rbnAdcIdleMode.Group;
			this.vbox5.Add (this.rbnAdcContSweep);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.rbnAdcContSweep]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox5]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.GtkAlignment1.Add (this.vbox4);
			this.frame2.Add (this.GtkAlignment1);
			this.lblADCConvMode = new global::Gtk.Label ();
			this.lblADCConvMode.Name = "lblADCConvMode";
			this.lblADCConvMode.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>ADC Conversion mode</b>");
			this.lblADCConvMode.UseMarkup = true;
			this.frame2.LabelWidget = this.lblADCConvMode;
			this.hbox3.Add (this.frame2);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.frame2]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.rbnAdcSpeed200 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("200 ksps"));
			this.rbnAdcSpeed200.CanFocus = true;
			this.rbnAdcSpeed200.Name = "rbnAdcSpeed200";
			this.rbnAdcSpeed200.DrawIndicator = true;
			this.rbnAdcSpeed200.UseUnderline = true;
			this.rbnAdcSpeed200.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox6.Add (this.rbnAdcSpeed200);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.rbnAdcSpeed200]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.rbnAdcSpeed250 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("250 ksps"));
			this.rbnAdcSpeed250.CanFocus = true;
			this.rbnAdcSpeed250.Name = "rbnAdcSpeed250";
			this.rbnAdcSpeed250.DrawIndicator = true;
			this.rbnAdcSpeed250.UseUnderline = true;
			this.rbnAdcSpeed250.Group = this.rbnAdcSpeed200.Group;
			this.vbox6.Add (this.rbnAdcSpeed250);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.rbnAdcSpeed250]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.rbnAdcSpeed333 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("333 ksps"));
			this.rbnAdcSpeed333.CanFocus = true;
			this.rbnAdcSpeed333.Name = "rbnAdcSpeed333";
			this.rbnAdcSpeed333.DrawIndicator = true;
			this.rbnAdcSpeed333.UseUnderline = true;
			this.rbnAdcSpeed333.Group = this.rbnAdcSpeed200.Group;
			this.vbox7.Add (this.rbnAdcSpeed333);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.rbnAdcSpeed333]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.rbnAdcSpeed400 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("400 ksps"));
			this.rbnAdcSpeed400.CanFocus = true;
			this.rbnAdcSpeed400.Name = "rbnAdcSpeed400";
			this.rbnAdcSpeed400.DrawIndicator = true;
			this.rbnAdcSpeed400.UseUnderline = true;
			this.rbnAdcSpeed400.Group = this.rbnAdcSpeed200.Group;
			this.vbox7.Add (this.rbnAdcSpeed400);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.rbnAdcSpeed400]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			this.vbox6.Add (this.vbox7);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vbox7]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.GtkAlignment2.Add (this.vbox6);
			this.frame3.Add (this.GtkAlignment2);
			this.GtkLabel13 = new global::Gtk.Label ();
			this.GtkLabel13.Name = "GtkLabel13";
			this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>ADC Conv. speed</b>");
			this.GtkLabel13.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel13;
			this.hbox4.Add (this.frame3);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame3]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			this.hbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
			w52.Position = 1;
			this.GtkAlignment.Add (this.hbox3);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel11 = new global::Gtk.Label ();
			this.GtkLabel11.Name = "GtkLabel11";
			this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>ADC settings</b>");
			this.GtkLabel11.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel11;
			this.vbox3.Add (this.frame1);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame1]));
			w55.Position = 0;
			w55.Expand = false;
			w55.Fill = false;
			this.notebook2.Add (this.vbox3);
			global::Gtk.Notebook.NotebookChild w56 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox3]));
			w56.Position = 1;
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("ADC/DAC");
			this.notebook2.SetTabLabel (this.vbox3, this.label1);
			this.label1.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnClear = new global::Gtk.Button ();
			this.btnClear.CanFocus = true;
			this.btnClear.Name = "btnClear";
			this.btnClear.UseUnderline = true;
			this.btnClear.Label = global::Mono.Unix.Catalog.GetString ("Clear log");
			this.table1.Add (this.btnClear);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnClear]));
			w57.LeftAttach = ((uint)(2));
			w57.RightAttach = ((uint)(3));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnReadAll = new global::Gtk.Button ();
			this.btnReadAll.CanFocus = true;
			this.btnReadAll.Name = "btnReadAll";
			this.btnReadAll.UseUnderline = true;
			this.btnReadAll.Label = global::Mono.Unix.Catalog.GetString ("Read all");
			this.table1.Add (this.btnReadAll);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnReadAll]));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnReadReg = new global::Gtk.Button ();
			this.btnReadReg.CanFocus = true;
			this.btnReadReg.Name = "btnReadReg";
			this.btnReadReg.UseUnderline = true;
			this.btnReadReg.Label = global::Mono.Unix.Catalog.GetString ("Read register");
			this.table1.Add (this.btnReadReg);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnReadReg]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnWriteReg = new global::Gtk.Button ();
			this.btnWriteReg.CanFocus = true;
			this.btnWriteReg.Name = "btnWriteReg";
			this.btnWriteReg.UseUnderline = true;
			this.btnWriteReg.Label = global::Mono.Unix.Catalog.GetString ("Write register");
			this.table1.Add (this.btnWriteReg);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnWriteReg]));
			w60.TopAttach = ((uint)(2));
			w60.BottomAttach = ((uint)(3));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblReadRes = new global::Gtk.Label ();
			this.lblReadRes.Name = "lblReadRes";
			this.table1.Add (this.lblReadRes);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblReadRes]));
			w61.TopAttach = ((uint)(1));
			w61.BottomAttach = ((uint)(2));
			w61.LeftAttach = ((uint)(2));
			w61.RightAttach = ((uint)(3));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spbReadReg = new global::Gtk.SpinButton (0, 127, 1);
			this.spbReadReg.CanFocus = true;
			this.spbReadReg.Name = "spbReadReg";
			this.spbReadReg.Adjustment.PageIncrement = 10;
			this.spbReadReg.ClimbRate = 1;
			this.spbReadReg.Numeric = true;
			this.table1.Add (this.spbReadReg);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table1 [this.spbReadReg]));
			w62.TopAttach = ((uint)(1));
			w62.BottomAttach = ((uint)(2));
			w62.LeftAttach = ((uint)(1));
			w62.RightAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spbWriteReg = new global::Gtk.SpinButton (0, 127, 1);
			this.spbWriteReg.CanFocus = true;
			this.spbWriteReg.Name = "spbWriteReg";
			this.spbWriteReg.Adjustment.PageIncrement = 10;
			this.spbWriteReg.ClimbRate = 1;
			this.spbWriteReg.Numeric = true;
			this.table1.Add (this.spbWriteReg);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table1 [this.spbWriteReg]));
			w63.TopAttach = ((uint)(2));
			w63.BottomAttach = ((uint)(3));
			w63.LeftAttach = ((uint)(1));
			w63.RightAttach = ((uint)(2));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spbWriteVal = new global::Gtk.SpinButton (0, 65535, 1);
			this.spbWriteVal.CanFocus = true;
			this.spbWriteVal.Name = "spbWriteVal";
			this.spbWriteVal.Adjustment.PageIncrement = 10;
			this.spbWriteVal.ClimbRate = 1;
			this.spbWriteVal.Numeric = true;
			this.table1.Add (this.spbWriteVal);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table1 [this.spbWriteVal]));
			w64.TopAttach = ((uint)(2));
			w64.BottomAttach = ((uint)(3));
			w64.LeftAttach = ((uint)(2));
			w64.RightAttach = ((uint)(3));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox7.Add (this.table1);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.table1]));
			w65.Position = 0;
			w65.Expand = false;
			w65.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txvLog = new global::Gtk.TextView ();
			this.txvLog.CanFocus = true;
			this.txvLog.Name = "txvLog";
			this.GtkScrolledWindow.Add (this.txvLog);
			this.hbox7.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.GtkScrolledWindow]));
			w67.Position = 1;
			this.notebook2.Add (this.hbox7);
			global::Gtk.Notebook.NotebookChild w68 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.hbox7]));
			w68.Position = 2;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Test");
			this.notebook2.SetTabLabel (this.hbox7, this.label5);
			this.label5.ShowAll ();
			this.hbox2.Add (this.notebook2);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.notebook2]));
			w69.Position = 0;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w70.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.vbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label3]));
			w71.Position = 1;
			w71.Expand = false;
			w71.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox2.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar1]));
			w72.Position = 2;
			w72.Expand = false;
			w72.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w73.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 768;
			this.DefaultHeight = 610;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.tbnQuit.Clicked += new global::System.EventHandler (this.OnTbnQuitClicked);
			this.tbnConnect.Toggled += new global::System.EventHandler (this.OnTbnConnectToggled);
			this.cmbPortNumber.Changed += new global::System.EventHandler (this.OnCmbPortNumberChanged);
			this.cmbPortMode.Changed += new global::System.EventHandler (this.OnCmbPortModeChanged);
			this.btnPortConfApply.Clicked += new global::System.EventHandler (this.OnBtnPortConfApplyClicked);
			this.rbnAdcSpeed200.Activated += new global::System.EventHandler (this.OnRbnAdcSpeedActivated);
			this.rbnAdcSpeed250.Activated += new global::System.EventHandler (this.OnRbnAdcSpeedActivated);
			this.rbnAdcSpeed333.Activated += new global::System.EventHandler (this.OnRbnAdcSpeedActivated);
			this.rbnAdcSpeed400.Activated += new global::System.EventHandler (this.OnRbnAdcSpeedActivated);
			this.spbReadReg.ValueChanged += new global::System.EventHandler (this.OnSpbReadRegValueChanged);
			this.btnWriteReg.Clicked += new global::System.EventHandler (this.OnBtnWriteRegClicked);
			this.btnReadReg.Clicked += new global::System.EventHandler (this.OnBtnReadRegClicked);
			this.btnReadAll.Clicked += new global::System.EventHandler (this.OnBtnReadAllClicked);
			this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearClicked);
		}
	}
}
